server:
  port: 8112

spring:
  application:
    name: department-services
  datasource:
    url: jdbc:postgresql://localhost:5432/department-service
    username: postgres
    password: Roman@18
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    

